insert into part_number_orange (name,description) values("BPI16A","Boitier Pied d'immeuble 16 Abonnés (au niveau chambre, pour résidence villas)");
insert into part_number_orange (name,description) values("BPI24A","Boitier Pied d'immeuble PBI 24 abonnés (au niveau sous sol, pour résidence Appartement) incluant K7 pour spliter");
insert into part_number_orange (name,description) values("BFI8A","Boitier façade immeuble connectorisé 8 abonnées");
insert into part_number_orange (name,description) values("PBO","Boitier d'étage PBO (au niveau de la colonne montante, pour résidence Appartement)");
insert into part_number_orange (name,description) values("1x2PLCSK7","1X2   PLC Splitter avec K7");
insert into part_number_orange (name,description) values("1x8PLCSK7","1X8   PLC Splitter avec K7");
insert into part_number_orange (name,description) values("1x32PLCSK8","1X32 PLC Splitter avec K7");
insert into part_number_orange (name,description) values("CFOIN48F G657A2","Optical Cable Fiber Indoor 48F G657A2 LSZH (au niveau de la colonne montante)");
insert into part_number_orange (name,description) values("CFOIN12F G657A2","Optical Cable Fiber Indoor 12F G657A2 LSZH (au niveau de la colonne montante)");
insert into part_number_orange (name,description) values("CFOIN24F G657A2","Optical Cable Fiber Indoor 24F G657A2 LSZH (au niveau de la colonne montante)");
insert into part_number_orange (name,description) values("BPE144FK7","Boite de dérivation de protection d'épissure BPE (au niveau de la chambre PNS 1) FO144 avec K7");
insert into part_number_orange (name,description) values("BPE72Fk7","Boite de dérivation de protection d'épissure BPE (au niveau de la chambre PNS 1) FO72 avec K7");
insert into part_number_orange (name,description) values("CFOOUT12F G652 D","Optical Cable Fiber Outdoor 12FO G652 D (au niveau conduite souterraine)");
insert into part_number_orange (name,description) values("CFOOUT144F G652 D µ","Câble fibre optique type conduite - 144 FO G652 D (Micro cable)");
insert into part_number_orange (name,description) values("CFOOUT72FM G652 D µ","Câble fibre optique type conduite - 72 FO G652 D (Micro Cable)");
insert into part_number_orange (name,description) values("CFOOUT72F G652 D SG","Câble fibre optique type conduite - 72 FO ( Simple Gaine)");
insert into part_number_orange (name,description) values("ODF12FO","ODF 12 FO");
insert into part_number_orange (name,description) values("ODF72FO","ODF 72 FO");
insert into part_number_orange (name,description) values("ODF144FO","ODF 144 FO");
