name: Mirror to ilogistics-mirror

on:
  push:
    branches: [ "master" ]  # Change if your primary branch has a different name

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for --mirror to work properly

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Mirror to destination
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/azdadanass/ilogistics-mirror.git
          git push --mirror mirror
