name: Mirror to ilogistics-mirror

on:
  push:
    branches: [ "master" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for --mirror to work properly

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Push to mirror (Authenticated)
        run: |
          # First validate we can access the repo
          if ! curl -s -H "Authorization: token ${{ secrets.MIRROR_PAT }}" \
            https://api.github.com/repos/azdadanass/ilogistics-mirror > /dev/null; then
            echo "::error::Failed to access mirror repository"
            exit 1
          fi
          
          # Perform the mirror push
          git remote add mirror "https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/azdadanass/ilogistics-mirror.git"
          git push --mirror mirror
