name: Mirror to ilogistics-mirror

on:
  push:
    branches: [ "master" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for --mirror to work properly

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Push to mirror
        run: |
          # Format: https://<USERNAME>:<PAT>@github.com/<REPO>.git
          git remote add mirror "https://azdadanass:${{ secrets.MIRROR_PAT }}@github.com/azdadanass/ilogistics-mirror.git"
          git push --mirror mirror
