name: Mirror to ilogistics-mirror

on:
  push:
    branches: [ "master" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Debug PAT access
        run: |
          echo "Testing PAT access to mirror repo"
          curl -i -H "Authorization: token ${{ secrets.MIRROR_PAT }}" \
            https://api.github.com/repos/azdadanass/ilogistics-mirror
          
          echo "Repository URL being used:"
          echo "https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/azdadanass/ilogistics-mirror.git"

      - name: Push to mirror
        run: |
          git remote add mirror "https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/azdadanass/ilogistics-mirror.git"
          git push --mirror mirror
